pluginManagement {
    repositories {
        maven {
            name 'MinecraftForge'
            url 'https://maven.minecraftforge.net'
        }
        maven {
            name 'Forge Staging'
            url 'https://maven.minecraftforge.net/releases'
        }
        gradlePluginPortal()
    }
}

rootProject.name = 'bedrock_enhancement'
