modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="bedrock_enhancement"
version="${version}"
displayName="Bedrock Enhancement"
description="Adds bedrock debris, bedrock tools, bedrock armor, and custom music to Minecraft."
authors="Eewin"
logoFile="bedrock_enhancement:icon.png"

[[dependencies.bedrock_enhancement]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bedrock_enhancement]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
